language: android

jdk:
  - openjdk8

android:
  components:
    - tools
    - build-tools-29.0.0
    - android-29
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease

after_script:
  - ls -ll
  - cd release
  - ls -ll

branches:
  only:
    - nightly